---
name: Statistics-RankOrder
version: 0.12
author:
  - David A Golden <dagolden@cpan.org>
abstract: |-
  Algorithms for determining overall rankings from 
  a panel of judges
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Accessor::Fast: 0.19
  Data::Dumper: 0
  Test::More: 0.45
  perl: 5.004
provides:
  Statistics::RankOrder:
    file: lib/Statistics/RankOrder.pm
    version: 0.12
generated_by: Module::Build version 0.2703
